/**
 * @file button_main.h
 * @brief Polled button task (25 ms) with event queue.
 */

#ifndef APP_BUTTON_MAIN_H_
#define APP_BUTTON_MAIN_H_

#include <stdbool.h>
#include <stdint.h>

/**
 * @brief Logical button events generated by the button task.
 */
typedef enum
{
    BUTTON_EVENT_NONE = 0, /**< No button event. */
    BUTTON_EVENT_UP_SHORT, /**< Short press of the UP button. */
    BUTTON_EVENT_DOWN_SHORT, /**< Short press of the DOWN button. */
    BUTTON_EVENT_OK_SHORT, /**< Short press of the OK button. */
    BUTTON_EVENT_OK_LONG /**< Long press of the OK button. */
} button_event_t;

/**
 * @brief Create the button polling task and event queue.
 */
void button_main_create_task(void);

/**
 * @brief Read one debounced button event from the queue.
 * @param evt [out] Destination for the event.
 * @param timeout_ms RTOS queue wait timeout in milliseconds.
 * @return `true` when an event was received.
 */
bool button_main_get_event(button_event_t *evt, uint32_t timeout_ms);

#endif /* APP_BUTTON_MAIN_H_ */
